title: "Naved124.github.io"
description: "Pentesting reports, writeups, notes"
author: "Naved Khan"
url: "https://naved124.github.io"

theme: minima

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md
  - projects.md

minima:
  skin: dark
  social_links:
    github: naved124
