title: "Naved124"
description: "Cybersecurity, CTF Writeups, and Pentesting Reports"
author: "Naved Khan"
url: "https://naved124.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom SASS
sass:
  sass_dir: _sass
  style: compressed

# Exclude list
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
